[package]
name = "problems"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"

[dev-dependencies]
env_logger = "0.8.3"
quickcheck = "1"
quickcheck_macros = "1"
